name: todo
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_storage: ^2.1.1
  get: ^4.6.6
  flutter_local_notifications: ^19.4.1
  # flutter_native_timezone: ^2.0.0  # Removed due to AGP compatibility issues
  firebase_core: ^4.0.0
  intl: ^0.20.2
  google_fonts: ^6.2.1
  date_picker_timeline: ^1.2.3
  sqflite: ^2.3.3+1
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.10+1
  rxdart: ^0.28.0
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "images/appicon.png"

flutter:
  uses-material-design: true

  assets:
    - images/person.jpeg
    - images/task.svg
